[package]
name = "auto-garden"
version = "0.1.0"
authors = ["Lonnie L. Souder <lonnie@souderfamily.net>"]
edition = "2018"

[dependencies]
sysfs_gpio = "0.5.3"
rocket = "0.4.0"
rocket_contrib = "0.4.0"
ws = "0.7.9"
rusqlite = "0.16.0"
